version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: django-mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Admin1234
      MYSQL_DATABASE: django_database
    volumes:
      - ./mysql-config/my.cnf:/etc/mysql/conf.d/my.cnf:ro
      - db_data:/var/lib/mysql

    command: >
      --default-authentication-plugin=mysql_native_password

volumes:
  db_data:
